# Database Configuration
DB_HOST=localhost
DB_PORT=5433
DB_NAME=DocusenseDb
DB_USERNAME=postgres
DB_PASSWORD=Tmanna

# OpenAI Configuration
OPENAI_API_KEY=YOUR_OPENAI_API_KEY_HERE

# JWT Configuration
JWT_SECRET=mySuperSecretKeyForJwtAuthentication123456
#JWT_EXPIRATION=864000000
